-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgLHNgXvYAeWaA2fnU
S6friyas/IxcNAaRwsX25NkHaDugCgYIKoZIzj0DAQehRANCAAQVicRtfaL8klg6
YnKctAuMC5xoTER0o/fzM02fAstL3AtYbfGv0fRhvUF4aBreNBFmrqKXgSTfUwaQ
FJuY+6Uf
-----END PRIVATE KEY-----